
# Redis provided by Docker (ports 13000, 11000)

web: bench serve  --port 8000


socketio: /home/sumit/.nvm/versions/node/v24.12.0/bin/node apps/frappe/socketio.js


watch: bench watch


schedule: bench schedule

worker:  bench worker 1>> logs/worker.log 2>> logs/worker.error.log

