dbfilename redis_queue.rdb
dir /home/sumit/projects/personal_repos/frappe_space/bench0/config/pids
pidfile /home/sumit/projects/personal_repos/frappe_space/bench0/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/sumit/projects/personal_repos/frappe_space/bench0/config/redis_queue.acl
