name: CI

env:
  FRAPPE_BENCH_IMAGE: frappe/bench@sha256:9c79fb8acd3e23a11e62aa6771f3426909303fddee39785adf645a0f2df7d208
  FRAPPE_BRANCH: version-15
  FRAPPE_COMMIT: 7abafc4824ec8d71e9127df965e54913bb41a870
  PRIMARY_SITE_NAME: horizon.localhost

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: main-horizon_crm-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.FRAPPE_BENCH_IMAGE }}
    strategy:
      fail-fast: false
    name: Server

    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup
        run: |
          bash "$GITHUB_WORKSPACE/docker/retry.sh" bench init --skip-redis-config-generation --skip-assets --frappe-branch "$FRAPPE_BRANCH" /home/frappe/frappe-bench
          bash "$GITHUB_WORKSPACE/docker/pin-frappe.sh" /home/frappe/frappe-bench

      - name: Install
        working-directory: /home/frappe/frappe-bench
        run: |
          bash "$GITHUB_WORKSPACE/docker/retry.sh" bench setup requirements --dev
          bench get-app horizon_crm $GITHUB_WORKSPACE
          bench new-site --db-root-username root --db-root-password root --admin-password admin --mariadb-user-host-login-scope='%' "$PRIMARY_SITE_NAME"
          bench --site "$PRIMARY_SITE_NAME" install-app horizon_crm
          bench --site "$PRIMARY_SITE_NAME" execute frappe.desk.page.setup_wizard.setup_wizard.setup_complete --args '[{"language":"English","email":"Administrator","full_name":"Administrator","password":"admin","country":"United States","timezone":"America/New_York","currency":"USD","enable_telemetry":0}]'
          bench build
        env:
          CI: 'Yes'

      - name: Run Tests
        working-directory: /home/frappe/frappe-bench
        run: |
          bench --site "$PRIMARY_SITE_NAME" set-config allow_tests true
          bench --site "$PRIMARY_SITE_NAME" run-tests --app horizon_crm
        env:
          TYPE: server
